# Generated by Django 4.2.17 on 2026-02-03 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0006_alter_foodtags_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodtags',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_tags', to='FilkaRecepty.taggroups'),
        ),
    ]
