# Generated by Django 4.2.17 on 2026-02-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0007_alter_foods_user_alter_foodtags_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='FilkaRecepty.foods'),
        ),
    ]
