# Generated by Django 4.2.17 on 2026-02-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0008_alter_ingredients_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefood',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='steps',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
