# Generated by Django 4.2.17 on 2026-02-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0009_alter_imagefood_position_alter_ingredients_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='search_name',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='foodtags',
            name='foodTag',
            field=models.CharField(error_messages={'unique': 'Toto označenie už v tejto skupine existuje.'}, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='taggroups',
            name='groupName',
            field=models.CharField(error_messages={'unique': 'Táto skupina už existuje.'}, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(error_messages={'unique': 'Táto jednotka už existuje.'}, max_length=60, unique=True),
        ),
    ]
