# Generated by Django 4.2.17 on 2026-02-18 09:36

import FilkaRecepty.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0010_foods_search_name_alter_foodtags_foodtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefood',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=FilkaRecepty.models.get_upload_path),
        ),
    ]
